import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    backgroundColor: '#ffcc00',
    paddingTop: 55,
    paddingHorizontal: 20,
    display: 'flex',
    flexDirection: 'column',
    paddingBottom: 20,
  },
  itemHeader: {
    width: '100%',
  },
  endereco: {
    paddingTop: 10,
    fontSize: 12,
    fontWeight: '600',
    color: '#000',
  },
  local: {
    paddingTop: 10,
  },

  listaHorizontalContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  itemCategoria: {
    alignItems: 'center',
    width: 'auto',
    marginHorizontal: 4,
  },
  imageContainer: {
    width: 65,
    height: 65,
    borderRadius: 12,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
    backgroundColor: '#f2f2f7',
    resizeMode: 'contain',
  },
  guiaRapido: {
    width: 45,
    height: 45,
    resizeMode: 'contain',
  },
  titleCategoria: {
    fontSize: 10,
    color: '#000000',
    textAlign: 'center',
  },
  bannerContainer: {
    marginHorizontal: 20,
    marginBottom: 25,
    borderRadius: 12,
    overflow: 'hidden',
  },
  imagemBanner: {
    width: '100%',
    height: 120,
    backgroundColor: '#ffcc00', 
    resizeMode: 'cover',
  },
  secaoProdutos: {
    marginBottom: 25,
  },
  tituloPromocao: {
    display: 'flex',
    flexDirection: 'row',
    textAlign: 'center',
    justifyContent: 'space-between',
  },
  tituloSecao: {
    fontSize: 18,
    fontWeight: 800,
    color: '#000',
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  subTituloSecao: {
    fontSize: 12,
    color: '#8e8e93',
    paddingHorizontal: 16,
  },
  listaProdutosContent: {
    paddingLeft: 20,
  },
  cardProduto: {
    width: 130,
    marginRight: 15,
  },
  fotoProduto: {
    width: 130,
    height: 120,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
    marginBottom: 8,
  },
  nomeProduto: {
    fontSize: 12,
    color: '#000',
    marginBottom: 4,
  },
  precoProduto: {
    fontSize: 17,
    fontWeight: 800,
    color: '#000',
  },
  botaoVerMais: {
    width: 130,
    height: 130,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
  },
  verMais: {
    display: 'flex',
    flexDirection: 'column',
  },
  textoVerMais: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#8e8e93',

  },
  listaVerticalContent: {
    paddingBottom: 80, 
  },
  cardRestaurante: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingBottom: 20,
    alignItems: 'flex-start',
  },
  fotoRestaurante: {
    width: 90,
    height: 90,
    borderRadius: 14,
    backgroundColor: '#F5F5F5',
  },
  infoRestaurante: {
    flex: 1,
    marginLeft: 15,
  },
  nomeRestaurante: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 4,
  },
  detalhesRestaurante: {
    fontSize: 13,
    color: '#666',
    marginBottom: 8,
  },
  textoTagPromocao: {
    alignSelf: 'flex-start',
    backgroundColor: '#ffe58a',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: 800,
    color: '#5c4a00',
  },
  logoContainer: {
    width: 140,
    height: 38,
    margin: 0,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  logoImage: {
    width: '100%',
    height: '100%',
    margin: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pesquisa: {
    width: '100%',
    height: '100%',
    padding: 7,
    borderWidth: 2,
    border: 'none',
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    borderRadius: 10,
    color: '#8e8e93',
  },
  caixaPesquisa: {
    width: '100%',
  },
  paraleloHeader: {
    display: 'flex',
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
  },
  location: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
  },
  lupa: {
    marginTop: 10,
  },
  inputPesquisa: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: 16,
    borderRadius: 40,
    backgroundColor: '#f2f2f7',
    marginBottom: 15,
    paddingVertical: 6,
  },
  section: {
    backgroundColor: '#fff',
    paddingTop: 24,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -20,
    flex: 1,
  },
  cupomTexto: {
    display: 'flex',
    flexDirection: 'row',
    width: '50%',
    paddingLeft: 5,
  },
  descricaoCupom: {
    display: 'flex',
    flexDirection: 'row',
    gap: 2,
  },
  textoCupom: {
    color: '#000',
    fontSize: 12,
    marginRight: 8,
    paddingBottom: 18,
  },
  cupomSection: {
    width: '100%',
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginTop: 30,
    marginBottom: 15,
  },
  cupomTitle: {
    fontSize: 24,
    fontWeight: 800,
    paddingBottom: 10,
    paddingLeft: 5,
  },
  cupom: {
    width: '100%',
    height: 72,
  },
  imagemCupom: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  secaoCupons: {
    marginBottom: 25,
  },
  listaCuponsContent: {
    paddingLeft: 14,
  },
  cardCupom: {
    width: 220,
    height: 120,
  },
  cupomImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  conteudo: {
    boxShadow: '0px 15px 50px rgba(0, 0, 0, 0.2)',
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 16,
    width: 'auto%',
    maxHeight: '50%',
  },
  tituloModal: {
    fontSize: 24, 
    fontWeight: 800,
  },
  subTituloModal: {
    fontSize: 17,
    fontWeight: 600,
    paddingTop: 16,
  },
  produtoModal: {
    alignItems: 'center',
  },
  fotoProdutoModal: {
    width: 130,
    height: 120,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
    marginBottom: 16,
    resizeMode: 'contain',
  },
  textoVerDetalhes: {
    fontSize: 12,
    color: '#8e8e93',
    paddingTop: 12,
  },
  conteudoDetalhes: {
    boxShadow: '0px 15px 50px rgba(0, 0, 0, 0.2)',
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 16,
    width: '90%',
    maxHeight: '85%',
  },
  linhaProdutoDetalhes: {
    flexDirection: 'row',
    gap: 15,
  },
  fotoDetalhes: {
    width: 90,
    height: 90,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
    resizeMode: 'contain',
  },
  infoDetalhes: {
    flex: 1,
  },
  nomeDetalhes: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
  },
  precoUnitario: {
    fontSize: 13,
    color: '#666',
    marginBottom: 8,
  },
  quantidadeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  quantidadeTexto: {
    fontSize: 17,
    fontWeight: 800,
    color: '#000',
  },
  lixeira: {
    marginLeft: 6,
  },
  categoriaDetalhes: {
    fontSize: 12,
    color: '#8e8e93',
    marginTop: 12,
  },
  totalBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#f2f2f7',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
  },
  textoTotal: {
    fontSize: 17,
    fontWeight: 800,
    color: '#000',
  },
  tituloOpcoes: {
    fontSize: 13,
    color: '#666',
    marginTop: 18,
    marginBottom: 8,
  },
  linhaOpcoes: {
    flexDirection: 'row',
    gap: 8,
  },
  opcao: {
    flex: 1,
    backgroundColor: '#f2f2f7',
    height: 40,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  opcaoEscolhida: {
    backgroundColor: '#ffcc00',
  },
  textoOpcao: {
    fontSize: 12,
    fontWeight: 800,
    color: '#000',
    textAlign: 'center',
  },
  botaoCarrinho: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#ffcc00',
    height: 48,
    borderRadius: 32,
    marginTop: 22,
  },
  textoBotaoCarrinho: {
    fontSize: 16,
    fontWeight: 800,
    color: '#000',
  },
  restaurantePouplarCard: {
    height: 65,
    width: 65,
    resizeMode: 'contain',
    backgroundColor: '#e1e1e3',
    borderRadius: 10,    
  },
  popularImage: {
    height: '100%',
    width: '100%',
    borderRadius: 10,
  },
  listaPopularesContent: {
    paddingHorizontal: 20,
    display: 'flex',
    flexDirection: 'row',
    gap: 12
  },
  secaoPopulares:{
    marginBottom: 25,
  },
  escolhaSection: {
    paddingVertical: 20,
    paddingHorizontal: 20,
    display: 'flex',
    flexDirection: 'row',
    gap: 20,
    width: '100%'
  },
  filtroItem: {
    backgroundColor: '#f2f2f7',
    paddingHorizontal: 16,
    width: 'auto',
    height: 40,
    borderRadius: 32,
    marginRight: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  textoFiltro: {
    textAlign: 'center',
    color: '#000000',
    fontWeight: 800,
  },
});